site_name: Zpark Lab
repo_url: https://github.com/agenteccentric/zpark-lab
site_url: https://agenteccentric.github.io/zpark-lab/
theme:
  name: material
  logo: assets/zpark-logo.png  # if you have one
  favicon: assets/favicon.ico  # optional
  palette:
    scheme: slate # or 'default' for dark/light toggle
    primary: indigo
    accent: blue
  font:
    text: Inter
    code: JetBrains Mono
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - header.autohide
    - content.code.annotate
extra_css:
  - stylesheets/modern.css  # (optional if we want custom styles later)

nav:
  - Home: index.md
  - Strategy:
      - Overview: strategy/index.md
      - Vision: strategy/vision.md
      - Stakeholders & Personas: strategy/personas.md
  - team-leadership:
      - Overview: team-leadership/index.md
  - Learning Paths: 
      - Overview: learning-paths/index.md
      - Sales Engineers: learning-paths/sales-engineers.md
      - Solutions Architects: learning-paths/solutions-architects.md
  - Certification:
      - Overview: certification/index.md
  - Impact & Metrics:
      - Overview: impact/index.md
  - Tools: 
      - Overview: tools/index.md
      - Databricks One: tools/databricks-one.md
      - LakeFlow: tools/lakeflow.md
      - Unity Catalog: tools/unity-catalog.md
  - AI & Automation:
      - Overview: ai/index.md
      - Claude/ChatGPT in Enablement: ai/ai-in-enablement.md
      - Prompting & Custom Bots: ai/prompting.md
  - Analytics & Feedback:
      - Overview: analytics/index.md
      - Measurement & Metrics: analytics/measurement.md
      - Usage & Feedback Loops: analytics/usage.md
  - DevOps for Enablement:
      - Overview: devops/index.md
      - GitHub Workflows: devops/github.md
      - CI/CD for Learning Content: devops/cicd.md
  - About: about.md