site_name: Crush Lab
nav:
  - Home: index.md
  - Enablement Strategy:
      - Overview: strategy/overview.md
      - Role Mapping: strategy/role-mapping.md
      - Stakeholders: strategy/stakeholders.md
  - Learning Paths:
      - Sales Engineer: learning-paths/sales-engineer.md
      - Solution Architect: learning-paths/solution-architect.md
  - Tools and Platforms:
      - Lakehouse Products Overview: tools/lakehouse.md
      - Genie & Lakeflow: tools/genie-lakeflow.md
      - Databricks One: tools/databricks-one.md
  - AI Integration:
      - Content Personalization: ai/content-personalization.md
      - Notebook-Driven Training: ai/notebooks.md
  - Analytics:
      - Success Metrics: analytics/metrics.md
      - Feedback Loops: analytics/feedback.md
  - GitHub & Automation:
      - CI/CD with MkDocs: devops/mkdocs-deploy.md
      - Integration with Databricks Notebooks: devops/databricks-notebooks.md
  - About: about.md
